[Interface]
Address = 10.200.0.2/24
PrivateKey = GM6Q2pxRIA4jm7SgdiNG3vxVfPO1fBCc8V9jq9i7BGQ=

[Peer]
PublicKey = A6DsF8AzVc6v3aB35Pfdj0bkVByYzvAAEzZ2NlS8riY=
Endpoint = tunnel-server:51820
AllowedIPs = 10.200.0.0/24
PersistentKeepalive = 25
