[Interface]
Address = 10.200.0.1/24
ListenPort = 51820
PrivateKey = MGuSvbe0dyVUmjJ2ERQbN+XLF9nD0OxfiMDK+axhEHY=

[Peer]
PublicKey = axsTckse3Uv1ITJmQDQCTwlCfH/kxldvZmf/ZNpV9X8=
AllowedIPs = 10.200.0.2/32
