---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-frp-operator-io-v1alpha1-exitserver
  failurePolicy: Fail
  name: vexitserver.kb.io
  rules:
  - apiGroups:
    - frp.operator.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - exitservers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-frp-operator-io-v1alpha1-tunnel
  failurePolicy: Fail
  name: vtunnel.kb.io
  rules:
  - apiGroups:
    - frp.operator.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - tunnels
  sideEffects: None
