{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "frp-operator.fullname" . }}-manager
  labels:
    {{- include "frp-operator.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["services/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["frp.operator.io"]
  resources:
    - exitclaims
    - exitpools
    - tunnels
    - localdockerproviderclasses
    - digitaloceanproviderclasses
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["frp.operator.io"]
  resources:
    - exitclaims/finalizers
    - exitpools/finalizers
    - tunnels/finalizers
    - localdockerproviderclasses/finalizers
    - digitaloceanproviderclasses/finalizers
  verbs: ["update"]
- apiGroups: ["frp.operator.io"]
  resources:
    - exitclaims/status
    - exitpools/status
    - tunnels/status
    - localdockerproviderclasses/status
    - digitaloceanproviderclasses/status
  verbs: ["get", "patch", "update"]
{{- end -}}
