{{- if .Values.metrics.serviceMonitor.enabled -}}
{{- if not .Values.metrics.service.enabled -}}
{{- fail "metrics.serviceMonitor.enabled requires metrics.service.enabled=true" -}}
{{- end -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "frp-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "frp-operator.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "frp-operator.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: https-metrics
    path: /metrics
    scheme: https
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
    {{- with .Values.metrics.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end -}}
