apiVersion: v2
name: frp-operator
description: Operator that manages frps tunnels via the four-CRD karpenter-shaped model.
type: application
version: 0.0.1
appVersion: 0.0.1
keywords:
  - frp
  - tunnel
  - operator
home: https://github.com/mtaku3/frp-operator
sources:
  - https://github.com/mtaku3/frp-operator
