name: E2E Tests

on:
  push:
  pull_request:

jobs:
  e2e-kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: helm/kind-action@v1.14.0
        with:
          install_only: true
      - run: make test-e2e
